# Travis configuration

language: python

dist: trusty
sudo: false

matrix:
    include:
        - os: linux
          python: 2.7
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 2.7
          env:
            - CXX=g++ CC=gcc

        - os: osx
          language: generic

addons:
    apt:
        packages:
            - pandoc
            - texlive-base

before_script:
  # Install system requirements for OSX (pylibpcap, libdnet and pandoc)
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      mkdir -p /Users/travis/Library/Python/2.7/lib/python/site-packages;
      echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/travis/Library/Python/2.7/lib/python/site-packages/homebrew.pth;
      brew update;
      brew install --with-python libdnet;
      brew install https://raw.githubusercontent.com/secdev/scapy/master/.travis/pylibpcap.rb;
      brew install openssl pandoc;
    fi
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

install:
  - pip2 install .
  - pip2 install flake8 six
  - pip2 install -r requirements-docs.txt
  - pip2 install -r requirements-optional.txt

script:
  - python setup.py test
  - python setup.py doc

before_deploy:
  # Build a source and wheel artifact
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
    provider: releases
    api_key:
        secure: jph0ZzpFytrPyZKm71s7LwaXvQ2QkGMM1DgwiBu4p9E99vAKvpNdVOXvyp4BmMp7PEksUKtPYpyGWIQCoTY7ffJUf72VbXLxLfsNqpGMP62UteVt5ssleYvpzVqfTt26gqGvsMZB2EhP9zpH3AgYaGuJIB1L0/CM+5Ilf3u2j4I=
    file:
        - "dist/*.whl"
        - "dist/*.tar.gz"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: CoreSecurity/pysap
